"""youtube-transcript-notes — lecture videos to readable, citable study notes."""

from .api import TranscriptFetcher
from .errors import (
    AcquisitionFailed,
    AgeRestricted,
    CaptionError,
    ConfigError,
    EmptyTranscript,
    InputUnreadable,
    LectureUnavailable,
    MalformedCaptions,
    MalformedCorrections,
    MalformedLecture,
    NoCaptionsAvailable,
    OutputError,
    OutputExists,
    OutputUnwritable,
    PayloadTooLarge,
    PlaylistEmpty,
    PlaylistNotSupported,
    PlaylistTooLarge,
    RegionBlocked,
    SeveralLectures,
    SourceError,
    TrackNotFound,
    TranscriptError,
    TransportContractChanged,
    TransportNotInstalled,
    UnknownCaptionFormat,
    UnknownProvider,
    UnknownRenderer,
)
from .models import (
    SCHEMA_VERSION,
    Chapter,
    Cue,
    Lecture,
    LectureMeta,
    Locator,
    Passage,
    Provenance,
    Section,
    TrustTier,
    Word,
    content_hash,
    format_date,
    format_timestamp,
)
from .parse import parse_captions
from .refine import ReflowPolicy, build_sections, policy_for, reflow
from .registry import Registry
from .render import Renderer, get_renderer, renderers
from .resolve import Track, TrackHandle, TrackManifest
from .sources import Expansion, SourceProvider, get_provider, provider_for, providers

__version__ = "0.3.0"

__all__ = [
    "SCHEMA_VERSION",
    "AcquisitionFailed",
    "AgeRestricted",
    "CaptionError",
    "Chapter",
    "ConfigError",
    "Cue",
    "EmptyTranscript",
    "Expansion",
    "InputUnreadable",
    "Lecture",
    "LectureMeta",
    "LectureUnavailable",
    "Locator",
    "MalformedCaptions",
    "MalformedCorrections",
    "MalformedLecture",
    "NoCaptionsAvailable",
    "OutputError",
    "OutputExists",
    "OutputUnwritable",
    "Passage",
    "PayloadTooLarge",
    "PlaylistEmpty",
    "PlaylistNotSupported",
    "PlaylistTooLarge",
    "Provenance",
    "ReflowPolicy",
    "RegionBlocked",
    "Registry",
    "Renderer",
    "Section",
    "SeveralLectures",
    "SourceError",
    "SourceProvider",
    "Track",
    "TrackHandle",
    "TrackManifest",
    "TrackNotFound",
    "TranscriptError",
    "TranscriptFetcher",
    "TransportContractChanged",
    "TransportNotInstalled",
    "TrustTier",
    "UnknownCaptionFormat",
    "UnknownProvider",
    "UnknownRenderer",
    "Word",
    "__version__",
    "build_sections",
    "content_hash",
    "format_date",
    "format_timestamp",
    "get_provider",
    "get_renderer",
    "parse_captions",
    "policy_for",
    "provider_for",
    "providers",
    "reflow",
    "renderers",
]
